# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-1431613-cachyos-x8664/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z010clg400-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl 
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    rt::set_parameter singleFileBasedDefaultNettype false
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/vedaant/Applications/2025.2/data/rsb/busdef
    /home/vedaant/school/quantum_work/linien/src
  } {
      /home/vedaant/Applications/2025.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /home/vedaant/Applications/2025.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -sv -lib work -include {
    /home/vedaant/Applications/2025.2/data/rsb/busdef
    /home/vedaant/school/quantum_work/linien/src
  } {
      /home/vedaant/school/quantum_work/linien/gateware/build/imports/home/vedaant/school/quantum_work/linien/src/ROM.sv
      /home/vedaant/school/quantum_work/linien/gateware/build/imports/home/vedaant/school/quantum_work/linien/src/arb_wave.sv
      /home/vedaant/school/quantum_work/linien/gateware/build/imports/home/vedaant/school/quantum_work/linien/src/bram.sv
      /home/vedaant/school/quantum_work/linien/gateware/build/imports/home/vedaant/school/quantum_work/linien/src/chirp_gen.sv
      /home/vedaant/school/quantum_work/linien/gateware/build/imports/home/vedaant/school/quantum_work/linien/src/control.sv
      /home/vedaant/school/quantum_work/linien/gateware/build/imports/home/vedaant/school/quantum_work/linien/src/delay.sv
      /home/vedaant/school/quantum_work/linien/gateware/build/imports/home/vedaant/school/quantum_work/linien/src/direct_jump.sv
      /home/vedaant/school/quantum_work/linien/gateware/build/imports/home/vedaant/school/quantum_work/linien/src/linear_ramp.sv
      /home/vedaant/school/quantum_work/linien/gateware/build/imports/home/vedaant/school/quantum_work/linien/src/sequence_top.sv
      /home/vedaant/school/quantum_work/linien/gateware/build/imports/home/vedaant/school/quantum_work/linien/src/sinusoid.sv
    }
      rt::read_verilog -lib work -include {
    /home/vedaant/Applications/2025.2/data/rsb/busdef
    /home/vedaant/school/quantum_work/linien/src
  } {
      /home/vedaant/school/quantum_work/linien/gateware/build/imports/home/vedaant/school/quantum_work/linien/gateware/verilog/axi_slave.v
      /home/vedaant/school/quantum_work/linien/gateware/build/imports/home/vedaant/school/quantum_work/linien/gateware/verilog/bus_clk_bridge.v
      /home/vedaant/school/quantum_work/linien/gateware/build/imports/home/vedaant/school/quantum_work/linien/gateware/verilog/processing_system7_v5_4_processing_system7.v
      /home/vedaant/school/quantum_work/linien/gateware/build/imports/home/vedaant/school/quantum_work/linien/gateware/verilog/red_pitaya_scope.v
      /home/vedaant/school/quantum_work/linien/gateware/build/imports/home/vedaant/school/quantum_work/linien/gateware/verilog/system_processing_system7_0_0.v
      /home/vedaant/school/quantum_work/linien/gateware/build/top.v
    }
      rt::read_vhdl -lib xpm /home/vedaant/Applications/2025.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top top
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-1431613-cachyos-x8664/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
uplevel #0 { 
   if {[info exists rt::doParallel] && $rt::doParallel} {
     rt::async_wait "asyncParallelOpen"
     rt::parallel_close
   }
   $rt::db resetHdlParse
   set hsKey [rt::get_parameter helper_shm_key] 
   if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
      $rt::db killSynthHelper $hsKey
   } 
   source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  }
 return -code "error" $rt::result
}
